# Various constants

DATETIME_FORMAT = "yyyy-MM-dd HH:mm:ss.SSSSSSS"

CHANGES_METADATA_FIELD_PREFIX = "header__"
CHANGES_METADATA_TIMESTAMP = "header__timestamp"
CHANGES_METADATA_OPERATION = "header__change_oper"

PARTITION_MAX_SIZE = 1073741824  # 1GB
